export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST'
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS'
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL'


